# JVM Settings
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true
org.gradle.configureondemand=false

# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx2048m

# Bypass lint error
android.lint.abortOnError=false
android.lint.checkTestSources=false

# ⚠️ FIX: Pakai KSP1 (KSP2 error di GitHub Actions)
ksp.useKSP2=false
