name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate keystore
        run: |
          keytool -genkeypair -v \
            -keystore debug.keystore \
            -storepass android \
            -keypass android \
            -alias androiddebugkey \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=Android Debug,O=Android,C=US"

      - name: Base64 - Bagian 1
        run: |
          base64 -w 0 debug.keystore > keystore.b64
          echo "===== BAGIAN 1/5 ====="
          head -c 600 keystore.b64
          echo ""

      - name: Base64 - Bagian 2
        run: |
          echo "===== BAGIAN 2/5 ====="
          tail -c +601 keystore.b64 | head -c 600
          echo ""

      - name: Base64 - Bagian 3
        run: |
          echo "===== BAGIAN 3/5 ====="
          tail -c +1201 keystore.b64 | head -c 600
          echo ""

      - name: Base64 - Bagian 4
        run: |
          echo "===== BAGIAN 4/5 ====="
          tail -c +1801 keystore.b64 | head -c 600
          echo ""

      - name: Base64 - Bagian 5
        run: |
          echo "===== BAGIAN 5/5 ====="
          tail -c +2401 keystore.b64
          echo ""

      - name: Upload keystore
        uses: actions/upload-artifact@v4
        with:
          name: debug-keystore
          path: |
            debug.keystore
            keystore.b64
          retention-days: 7
