name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate keystore
        run: |
          keytool -genkeypair -v \
            -keystore debug.keystore \
            -storepass android \
            -keypass android \
            -alias androiddebugkey \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=Android Debug,O=Android,C=US"

      - name: Convert to Base64
        run: |
          base64 -w 0 debug.keystore > keystore.b64
          echo "Panjang base64: $(wc -c < keystore.b64) karakter"

      - name: Upload keystore
        uses: actions/upload-artifact@v4
        with:
          name: debug-keystore
          path: |
            debug.keystore
            keystore.b64
          retention-days: 7
